[2025-02-02T18:01:04.420+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T18:01:04.438+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind_etl.extract_orders scheduled__2024-07-09T08:00:00+00:00 [queued]>
[2025-02-02T18:01:04.447+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind_etl.extract_orders scheduled__2024-07-09T08:00:00+00:00 [queued]>
[2025-02-02T18:01:04.448+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-02T18:01:04.464+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_orders> on 2024-07-09 08:00:00+00:00
[2025-02-02T18:01:04.474+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1077) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-02T18:01:04.475+0000] {standard_task_runner.py:72} INFO - Started process 1093 to run task
[2025-02-02T18:01:04.474+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'northwind_etl', 'extract_orders', 'scheduled__2024-07-09T08:00:00+00:00', '--job-id', '200', '--raw', '--subdir', 'DAGS_FOLDER/northwind_etl/northwind_etl.py', '--cfg-path', '/tmp/tmp8rl_kr91']
[2025-02-02T18:01:04.476+0000] {standard_task_runner.py:105} INFO - Job 200: Subtask extract_orders
[2025-02-02T18:01:04.531+0000] {task_command.py:467} INFO - Running <TaskInstance: northwind_etl.extract_orders scheduled__2024-07-09T08:00:00+00:00 [running]> on host dab7efa052da
[2025-02-02T18:01:04.622+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabriel' AIRFLOW_CTX_DAG_ID='northwind_etl' AIRFLOW_CTX_TASK_ID='extract_orders' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T08:00:00+00:00'
[2025-02-02T18:01:04.626+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T18:01:04.645+0000] {logging_mixin.py:190} INFO - table: orders, date: {{ds}}
[2025-02-02T18:01:04.646+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/northwind_etl/northwind_etl.py", line 30, in _lab_extrat_table_to_parquet
    engine = create_engine(POSTGRES_CONN)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 516, in create_engine
    u, plugins, kwargs = u._instantiate_plugins(kwargs)
                         ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_instantiate_plugins'
[2025-02-02T18:01:04.660+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=northwind_etl, task_id=extract_orders, run_id=scheduled__2024-07-09T08:00:00+00:00, execution_date=20240709T080000, start_date=20250202T180104, end_date=20250202T180104
[2025-02-02T18:01:04.730+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T18:01:04.734+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 200 for task extract_orders ('NoneType' object has no attribute '_instantiate_plugins'; 1093)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/northwind_etl/northwind_etl.py", line 30, in _lab_extrat_table_to_parquet
    engine = create_engine(POSTGRES_CONN)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 516, in create_engine
    u, plugins, kwargs = u._instantiate_plugins(kwargs)
                         ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_instantiate_plugins'
[2025-02-02T18:01:04.772+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-02T18:01:04.792+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-02T18:01:04.794+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-05T02:26:21.521+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-05T02:26:21.548+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind_etl.extract_orders scheduled__2024-07-09T08:00:00+00:00 [queued]>
[2025-02-05T02:26:21.559+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind_etl.extract_orders scheduled__2024-07-09T08:00:00+00:00 [queued]>
[2025-02-05T02:26:21.559+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-05T02:26:21.576+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_orders> on 2024-07-09 08:00:00+00:00
[2025-02-05T02:26:21.587+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=15441) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-05T02:26:21.588+0000] {standard_task_runner.py:72} INFO - Started process 15473 to run task
[2025-02-05T02:26:21.587+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'northwind_etl', 'extract_orders', 'scheduled__2024-07-09T08:00:00+00:00', '--job-id', '449', '--raw', '--subdir', 'DAGS_FOLDER/northwind_etl/northwind_etl.py', '--cfg-path', '/tmp/tmpd6sbc037']
[2025-02-05T02:26:21.589+0000] {standard_task_runner.py:105} INFO - Job 449: Subtask extract_orders
[2025-02-05T02:26:21.643+0000] {task_command.py:467} INFO - Running <TaskInstance: northwind_etl.extract_orders scheduled__2024-07-09T08:00:00+00:00 [running]> on host 09d05643d017
[2025-02-05T02:26:21.750+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabriel' AIRFLOW_CTX_DAG_ID='northwind_etl' AIRFLOW_CTX_TASK_ID='extract_orders' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T08:00:00+00:00'
[2025-02-05T02:26:21.752+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-05T02:26:21.772+0000] {logging_mixin.py:190} INFO - table: orders, date: 2024-07-09
[2025-02-05T02:26:21.820+0000] {logging_mixin.py:190} INFO - Total records extracted: 830
[2025-02-05T02:26:21.821+0000] {logging_mixin.py:190} INFO - Columns present: order_id, customer_id, employee_id, order_date, required_date, shipped_date, ship_via, freight, ship_name, ship_address, ship_city, ship_region, ship_postal_code, ship_country
[2025-02-05T02:26:21.871+0000] {logging_mixin.py:190} INFO - Extraction saved successfully at: /opt/***/data/postgres/orders/2024-07-09/orders.parquet
[2025-02-05T02:26:21.872+0000] {python.py:240} INFO - Done. Returned value was: Extracted 830 records from orders
[2025-02-05T02:26:21.899+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-05T02:26:21.900+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=northwind_etl, task_id=extract_orders, run_id=scheduled__2024-07-09T08:00:00+00:00, execution_date=20240709T080000, start_date=20250205T022621, end_date=20250205T022621
[2025-02-05T02:26:21.924+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-05T02:26:21.944+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-05T02:26:21.947+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
